# Generated by Django 4.1.2 on 2022-10-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='tx_name', max_length=64)),
                ('abbreviation', models.CharField(db_column='tx_abbreviation', max_length=2)),
            ],
            options={
                'db_table': 'state',
                'managed': True,
            },
        ),
    ]
